version: 2.1
orbs:
  node: circleci/node@5.0.3
  aws-cli: circleci/aws-cli@3.1.4
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  full-stack-deployment:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: installing-client-packages
          command: npm run client:install
      - run:
          name: testing-client
          command: npm run client:test
      - run:
          name: client-build
          command: npm run client:build
      - run:
          name: client-deploy
          command: npm run client:deploy
      - run:
          name: eb-version
          command: eb --version
      - run:
          name: backend-install
          command: npm run server:install
      - run:
          name: backend-deploy
          command: npm run server:deploy

workflows:
  frontend-build-and-deploy:
    jobs:
      - full-stack-deployment:
          filters:
            branches:
              only:
                - main
